DELETE FROM Feedback;
DELETE FROM Rezervare;
DELETE FROM Profil_Client;
DELETE FROM Client;
DELETE FROM Proiectie;
DELETE FROM Film;
DELETE FROM Sala;
DELETE FROM Cinema;

DROP TABLE Feedback CASCADE CONSTRAINTS;
DROP TABLE Rezervare CASCADE CONSTRAINTS;
DROP TABLE Profil_Client CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Proiectie CASCADE CONSTRAINTS;
DROP TABLE Film CASCADE CONSTRAINTS;
DROP TABLE Sala CASCADE CONSTRAINTS;
DROP TABLE Cinema CASCADE CONSTRAINTS;


DROP SEQUENCE Cinema_id_cinema_SEQ;
DROP SEQUENCE Client_id_client_SEQ;
DROP SEQUENCE Feedback_id_feedback_SEQ;
DROP SEQUENCE Film_id_film_SEQ;
DROP SEQUENCE Profil_Client_id_profil_SEQ;
DROP SEQUENCE Proiectie_id_proiectie_SEQ;
DROP SEQUENCE Rezervare_id_rezervare_SEQ;
DROP SEQUENCE Sala_id_sala_SEQ;
