-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-18 22:55:11 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cinema 
    ( 
     id_cinema NUMBER (6)  NOT NULL , 
     Oras      VARCHAR2 (22)  NOT NULL , 
     Strada    VARCHAR2 (30)  NOT NULL , 
     Telefon   CHAR (10)  NOT NULL , 
     Email     VARCHAR2 (30)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Cinema 
    ADD CONSTRAINT oras_ck 
    CHECK (length(Oras) > 1) 
;

ALTER TABLE Cinema 
    ADD CONSTRAINT strada_ck 
    CHECK (length(Strada) > 1) 
;

ALTER TABLE Cinema 
    ADD CONSTRAINT telefon_cinema_ck 
    CHECK (regexp_like(Telefon, '^07[0-9]{8}$')) 
;

ALTER TABLE Cinema 
    ADD CONSTRAINT cinema_email 
    CHECK (regexp_like(Email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Cinema 
    ADD CONSTRAINT Cinema_PK PRIMARY KEY ( id_cinema ) ;

ALTER TABLE Cinema 
    ADD CONSTRAINT Cinema_Telefon_UN UNIQUE ( Telefon ) ;

ALTER TABLE Cinema 
    ADD CONSTRAINT Cinema_Email_UN UNIQUE ( Email ) ;

CREATE TABLE Client 
    ( 
     id_client NUMBER (8)  NOT NULL , 
     Email     VARCHAR2 (30) , 
     Nume      VARCHAR2 (25)  NOT NULL , 
     Telefon   CHAR (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Client 
    ADD CONSTRAINT client_email_ck 
    CHECK (regexp_like(Email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT nume_ck 
    CHECK (length(Nume) > 1) 
;

ALTER TABLE Client 
    ADD CONSTRAINT telefon_client_ck 
    CHECK (regexp_like(Telefon, '^07[0-9]{8}$')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT Client_PK PRIMARY KEY ( id_client ) ;

ALTER TABLE Client 
    ADD CONSTRAINT Client_Email_UN UNIQUE ( Email ) ;

ALTER TABLE Client 
    ADD CONSTRAINT Client_Telefon_UN UNIQUE ( Telefon ) ;

CREATE TABLE Feedback 
    ( 
     id_feedback   NUMBER  NOT NULL , 
     Recenzie      VARCHAR2 (250) , 
     data_recenzie DATE  NOT NULL , 
     Rating        NUMBER (2)  NOT NULL , 
     id_rezervare  NUMBER (8)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Recenzie_ck 
    CHECK (length(Recenzie)>0) 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Rating_ck 
    CHECK (Rating BETWEEN 1 AND 10) 
;
CREATE UNIQUE INDEX Feedback__IDX ON Feedback 
    ( 
     id_rezervare ASC 
    ) 
    LOGGING 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_PK PRIMARY KEY ( id_feedback ) ;

CREATE TABLE Film 
    ( 
     id_film           NUMBER (6)  NOT NULL , 
     Titlu             VARCHAR2 (25)  NOT NULL , 
     Durata            NUMBER (3) DEFAULT 90  NOT NULL , 
     Gen               VARCHAR2 (15)  NOT NULL , 
     Descriere         VARCHAR2 (200) , 
     Restrictie_varsta NUMBER (2) 
    ) 
    LOGGING 
;

ALTER TABLE Film 
    ADD CONSTRAINT Titlu_ck 
    CHECK (length(Titlu) > 1) 
;

ALTER TABLE Film 
    ADD CONSTRAINT Durata_ck 
    CHECK (Durata BETWEEN 60 AND 240) 
;

ALTER TABLE Film 
    ADD CONSTRAINT Gen_ck 
    CHECK (Gen IN ('Actiune', 'Aventura', 'Comedie', 'Documentar', 'Drama', 'Fantasy', 'Horror', 'Romantic', 'Science-Fiction', 'Thriller')) 
;

ALTER TABLE Film 
    ADD CONSTRAINT Descriere_ck 
    CHECK (Descriere IS NULL OR length(Descriere)>10) 
;

ALTER TABLE Film 
    ADD CONSTRAINT restrictie_varsta_ck 
    CHECK (Restrictie_varsta IN (3, 7, 12, 15, 18)) 
;

ALTER TABLE Film 
    ADD CONSTRAINT Film_PK PRIMARY KEY ( id_film ) ;

ALTER TABLE Film 
    ADD CONSTRAINT Film_Titlu_UN UNIQUE ( Titlu ) ;

CREATE TABLE Profil_Client 
    ( 
     id_profil     NUMBER (8)  NOT NULL , 
     nume          VARCHAR2 (15)  NOT NULL , 
     prenume       VARCHAR2 (15)  NOT NULL , 
     numar_telefon CHAR (10)  NOT NULL , 
     data_nasterii DATE  NOT NULL , 
     parola        VARCHAR2 (25)  NOT NULL , 
     adresa        VARCHAR2 (50) , 
     email         VARCHAR2 (30)  NOT NULL , 
     id_client     NUMBER (8)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT nume_profil_ck 
    CHECK (length(nume)>2) 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT prenume_profil_ck 
    CHECK (length(prenume)>2) 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT nr_tel_profil_ck 
    CHECK (regexp_like(numar_telefon, '^07[0-9]{8}$')) 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT parola_profil_ck 
    CHECK (length(parola)>8) 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT adresa_profil_ck 
    CHECK (regexp_like(adresa, '^[A-Z][a-zA-ZăâîșțĂÂÎȘȚ]+,\s+[Ss]tr(ada|\.|)\s+[A-Z][a-zA-ZăâîșțĂÂÎȘȚ ]+\s+[0-9]{1,3}[A-Za-z]?$')) 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT email_profil_ck 
    CHECK (regexp_like(email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;
CREATE UNIQUE INDEX Profil_Client__IDX ON Profil_Client 
    ( 
     id_client ASC 
    ) 
    LOGGING 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT Profil_Client_PK PRIMARY KEY ( id_profil ) ;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT Profil_Client_email_UN UNIQUE ( email ) ;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT Profil_Client_numar_telefon_UN UNIQUE ( numar_telefon ) ;

CREATE TABLE Proiectie 
    ( 
     id_proiectie  NUMBER (8)  NOT NULL , 
     Data          DATE  NOT NULL , 
     ora_inceput   VARCHAR2 (5) DEFAULT '12:00'  NOT NULL , 
     ora_sfarsit   VARCHAR2 (5) DEFAULT '14:00'  NOT NULL , 
     id_film       NUMBER (6)  NOT NULL , 
     id_sala       NUMBER (6)  NOT NULL , 
     tip_proiectie VARCHAR2 (4) DEFAULT '3D'  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT ora_inceput_ck 
    CHECK (ora_inceput IN ('10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '8:00', '9:00')) 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT ora_sfarsit_ck 
    CHECK (ora_sfarsit IN ('10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '9:00')) 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT tip_proiectie_ck 
    CHECK (tip_proiectie IN ('2D', '3D', '4DX', 'IMAX')) 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT Proiectie_PK PRIMARY KEY ( id_proiectie ) ;

CREATE TABLE Rezervare 
    ( 
     id_rezervare     NUMBER (8)  NOT NULL , 
     numar_locuri     NUMBER (3) DEFAULT 1  NOT NULL , 
     locuri_rezervate VARCHAR2 (7)  NOT NULL , 
     data_rez         DATE  NOT NULL , 
     status_rezervare CHAR (8) DEFAULT 'REZERVAT'  NOT NULL , 
     id_proiectie     NUMBER (8)  NOT NULL , 
     id_client        NUMBER (8)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT numar_locuri_ck 
    CHECK (numar_locuri>0) 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT locuri_rez_ck 
    CHECK (REGEXP_LIKE(locuri_rezervate, '^R[0-9]+-C[0-9]+$')) 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT rezervare_status_ck 
    CHECK (status_rezervare IN ('ACHITAT', 'REZERVAT')) 
;

COMMENT ON COLUMN Rezervare.locuri_rezervate IS 'Formatul rezervarii sa fie de genul: R1-C1 (randul 1 coloana 1)' 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT Rezervare_PK PRIMARY KEY ( id_rezervare ) ;

CREATE TABLE Sala 
    ( 
     id_sala    NUMBER (6)  NOT NULL , 
     Capacitate NUMBER (3) DEFAULT 100  NOT NULL , 
     nr_rand    NUMBER (2) DEFAULT 10  NOT NULL , 
     nr_col     NUMBER (2) DEFAULT 10  NOT NULL , 
     id_cinema  NUMBER (6)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Sala 
    ADD CONSTRAINT capacitate_ck 
    CHECK (Capacitate BETWEEN 50 AND 300) 
;

ALTER TABLE Sala 
    ADD CONSTRAINT nr_rand_ck 
    CHECK (nr_rand>4) 
;

ALTER TABLE Sala 
    ADD CONSTRAINT nr_col_ck 
    CHECK (nr_col>4) 
;

ALTER TABLE Sala 
    ADD CONSTRAINT Sala_PK PRIMARY KEY ( id_sala ) ;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_Rezervare_FK FOREIGN KEY 
    ( 
     id_rezervare
    ) 
    REFERENCES Rezervare 
    ( 
     id_rezervare
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Profil_Client 
    ADD CONSTRAINT Profil_Client_Client_FK FOREIGN KEY 
    ( 
     id_client
    ) 
    REFERENCES Client 
    ( 
     id_client
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT Proiectie_Film_FK FOREIGN KEY 
    ( 
     id_film
    ) 
    REFERENCES Film 
    ( 
     id_film
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Proiectie 
    ADD CONSTRAINT Proiectie_Sala_FK FOREIGN KEY 
    ( 
     id_sala
    ) 
    REFERENCES Sala 
    ( 
     id_sala
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT Rezervare_Client_FK FOREIGN KEY 
    ( 
     id_client
    ) 
    REFERENCES Client 
    ( 
     id_client
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Rezervare 
    ADD CONSTRAINT Rezervare_Proiectie_FK FOREIGN KEY 
    ( 
     id_proiectie
    ) 
    REFERENCES Proiectie 
    ( 
     id_proiectie
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Sala 
    ADD CONSTRAINT Sala_Cinema_FK FOREIGN KEY 
    ( 
     id_cinema
    ) 
    REFERENCES Cinema 
    ( 
     id_cinema
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER data_proiectie 
    BEFORE INSERT OR UPDATE ON Proiectie 
    FOR EACH ROW 
    ENABLE 
BEGIN
IF(:new.Data <= SYSDATE) THEN
  RAISE_APPLICATION_ERROR(-20001, 'Data proiectiei trebuie sa fie in viitor.');
END IF;
END; 
/

CREATE OR REPLACE TRIGGER data_recenzie 
    BEFORE INSERT OR UPDATE ON Feedback 
    FOR EACH ROW 
    ENABLE 
BEGIN
IF(:new.data_recenzie <= SYSDATE) THEN
  RAISE_APPLICATION_ERROR(-20001, 'Data proiectiei trebuie sa fie in viitor.');
END IF;
END; 
/

CREATE OR REPLACE TRIGGER data_rezervare 
    BEFORE INSERT OR UPDATE ON Rezervare 
    FOR EACH ROW 
    ENABLE 
BEGIN
IF(:new.data_rez <= SYSDATE) THEN
  RAISE_APPLICATION_ERROR(-20001, 'Data proiectiei trebuie sa fie in viitor.');
END IF;
END; 
/

CREATE OR REPLACE TRIGGER verifica_durata_film 
    BEFORE INSERT OR UPDATE ON Proiectie 
    FOR EACH ROW 
    ENABLE 
DECLARE
    v_durata NUMBER;
    v_ora_inceput DATE;
    v_ora_sfarsit_calc DATE;
BEGIN
    SELECT Durata INTO v_durata FROM Film WHERE id_film = :NEW.id_film;

    v_ora_inceput := TO_DATE(:NEW.ora_inceput, 'HH24:MI');
    v_ora_sfarsit_calc := v_ora_inceput + (v_durata/1440);  

    IF v_ora_sfarsit_calc > TO_DATE(:NEW.ora_sfarsit,'HH24:MI') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Durata filmului depaseste intervalul orar selectat.');
    END IF;
END; 
/

CREATE OR REPLACE TRIGGER verifica_loc_unic 
    BEFORE INSERT OR UPDATE ON Rezervare 
    FOR EACH ROW 
    ENABLE 
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM Rezervare r
    WHERE r.id_proiectie = :NEW.id_proiectie
      AND r.id_client <> :NEW.id_client
      AND r.locuri_rezervate = :NEW.locuri_rezervate;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004,
            'Locul ales este deja rezervat de alt client.');
    END IF;
END; 
/

CREATE OR REPLACE TRIGGER verifica_suprapunere_proiectie 
    BEFORE INSERT OR UPDATE ON Proiectie 
    FOR EACH ROW 
    ENABLE 
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM Proiectie
    WHERE id_sala = :NEW.id_sala
      AND Data = :NEW.Data
      AND (
            (TO_DATE(:NEW.ora_inceput, 'HH24:MI') BETWEEN TO_DATE(ora_inceput, 'HH24:MI') AND TO_DATE(ora_sfarsit, 'HH24:MI'))
         OR (TO_DATE(:NEW.ora_sfarsit, 'HH24:MI') BETWEEN TO_DATE(ora_inceput, 'HH24:MI') AND TO_DATE(ora_sfarsit, 'HH24:MI'))
         OR (TO_DATE(ora_inceput, 'HH24:MI') BETWEEN TO_DATE(:NEW.ora_inceput, 'HH24:MI') AND TO_DATE(:NEW.ora_sfarsit, 'HH24:MI'))
          )
      AND (:NEW.id_proiectie IS NULL OR id_proiectie <> :NEW.id_proiectie);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Exista deja o proiectie in aceeasi sala si zi care se suprapune ca interval orar.');
    END IF;
END; 
/

CREATE SEQUENCE Cinema_id_cinema_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Cinema_id_cinema_TRG 
BEFORE INSERT ON Cinema 
FOR EACH ROW 
WHEN (NEW.id_cinema IS NULL) 
BEGIN 
    :NEW.id_cinema := Cinema_id_cinema_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Client_id_client_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Client_id_client_TRG 
BEFORE INSERT ON Client 
FOR EACH ROW 
WHEN (NEW.id_client IS NULL) 
BEGIN 
    :NEW.id_client := Client_id_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Feedback_id_feedback_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Feedback_id_feedback_TRG 
BEFORE INSERT ON Feedback 
FOR EACH ROW 
WHEN (NEW.id_feedback IS NULL) 
BEGIN 
    :NEW.id_feedback := Feedback_id_feedback_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Film_id_film_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Film_id_film_TRG 
BEFORE INSERT ON Film 
FOR EACH ROW 
WHEN (NEW.id_film IS NULL) 
BEGIN 
    :NEW.id_film := Film_id_film_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Profil_Client_id_profil_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Profil_Client_id_profil_TRG 
BEFORE INSERT ON Profil_Client 
FOR EACH ROW 
WHEN (NEW.id_profil IS NULL) 
BEGIN 
    :NEW.id_profil := Profil_Client_id_profil_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Proiectie_id_proiectie_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Proiectie_id_proiectie_TRG 
BEFORE INSERT ON Proiectie 
FOR EACH ROW 
WHEN (NEW.id_proiectie IS NULL) 
BEGIN 
    :NEW.id_proiectie := Proiectie_id_proiectie_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Rezervare_id_rezervare_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Rezervare_id_rezervare_TRG 
BEFORE INSERT ON Rezervare 
FOR EACH ROW 
WHEN (NEW.id_rezervare IS NULL) 
BEGIN 
    :NEW.id_rezervare := Rezervare_id_rezervare_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Sala_id_sala_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Sala_id_sala_TRG 
BEFORE INSERT ON Sala 
FOR EACH ROW 
WHEN (NEW.id_sala IS NULL) 
BEGIN 
    :NEW.id_sala := Sala_id_sala_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             51
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          14
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          8
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
